[package]
name = "implement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
proc-macro2 = "1.0.69"
quote = "1.0.33"
